Added check_anchor2_backup

diff --git a/bin/file-age-seconds b/bin/file-age-seconds
--- a/bin/file-age-seconds
+++ b/bin/file-age-seconds
@@ -4,9 +4,13 @@
 
 function fileAgeSeconds {
 	local filename=$1
+	if [[ -z $filename ]] || [[ ! -f $filename ]]; then
+		echo "ERROR: can't find file: $filename" >&2
+		exit 1
+	fi
 	modsecs=$(date --utc --reference=$filename +%s)
 	nowsecs=$(date +%s)
-	delta=$(($nowsecs-$modsecs))
+	delta=$(( $nowsecs - $modsecs ))
 	echo  $delta
 }
 
